[tasks.pre-coverage]
install_crate = "cargo-nextest"

[tasks.coverage]
env = { RUST_LOG = "trace", NEXTEST_TEST_THREADS = 200 }
script = '''
cargo llvm-cov nextest --all-features --lcov --ignore-filename-regex ".cargo|.*_test\.rs" > ./target/debug/lcov.info
genhtml -o ./target/debug/coverage/ --show-details --ignore-errors source --legend ./target/debug/lcov.info
'''
clear = true
install_crate = { binary = "cargo-llvm-cov", rustup_component_name = "llvm-tools-preview" }
dependencies = ["pre-coverage"]

[tasks.view-coverage]
script = '''
xdg-open ./target/debug/coverage/index.html
'''
dependencies = ["coverage"]

[tasks.view-coverage.windows]
script = '''
./target/debug/coverage/index.html
'''
dependencies = ["coverage"]
script_runner = "@shell"
